//// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//import java.util.*;
//import java.util.concurrent.TimeUnit;
//
//public class AddCardTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    System.setProperty("webdriver.chrome.driver", "D:\\Загрузки\\chromedriver_win32\\chromedriver.exe");
//
//    driver = new ChromeDriver();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void addCard() {
//    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
//
//    driver.get("https://trello.com/");
//    driver.manage().window().setSize(new Dimension(1536, 824));
//    driver.findElement(By.linkText("Войти")).click();
//    driver.findElement(By.id("user")).sendKeys("marinarhipova5@gmail.com");
//    driver.findElement(By.id("password")).click();
//    driver.findElement(By.id("password")).sendKeys("53wr67qpt");
//    driver.findElement(By.id("login")).click();
//
//    driver.findElement(By.xpath("(//div[@style='overflow: hidden; text-overflow: ellipsis; -webkit-box-orient: vertical; display: -webkit-box; -webkit-line-clamp: 2;'][contains(.,'Hi, test')])[1]")).click();
//    driver.findElement(By.xpath("//span[@class='js-add-a-card'][contains(.,'Добавить карточку')]"));
//
////    {
////      WebElement element = driver.findElement(By.cssSelector(".boards-page-board-section:nth-child(2) .boards-page-board-section-list-item:nth-child(1) .board-tile-fade"));
////      Actions builder = new Actions(driver);
////      builder.moveToElement(element).perform();
////    }
////    {
////      WebElement element = driver.findElement(By.tagName("body"));
////      Actions builder = new Actions(driver);
////      builder.moveToElement(element, 0, 0).perform();
////    }
////    driver.findElement(By.cssSelector(".boards-page-board-section:nth-child(2) .boards-page-board-section-list-item:nth-child(1) .board-tile-details")).click();
////    js.executeScript("window.scrollTo(0,0)");
////    {
////      WebElement element = driver.findElement(By.cssSelector(".open-card-composer"));
////      Actions builder = new Actions(driver);
////      builder.moveToElement(element).perform();
////    }
////    driver.findElement(By.cssSelector(".open-card-composer")).click();
////    {
////      WebElement element = driver.findElement(By.tagName("body"));
////      Actions builder = new Actions(driver);
////      builder.moveToElement(element, 0, 0).perform();
////    }
////    driver.findElement(By.name("//textarea[contains(@class,'list-card-composer-textarea js-card-title')]"));
//    driver.findElement(By.xpath("//span[@class='js-add-a-card'][contains(.,'Добавить карточку')]")).click();
//    driver.findElement(By.className(".list-card-composer-textarea js-card-title")).sendKeys("Hi");
//    driver.findElement(By.xpath("//input[contains(@class,'primary confirm mod-compact js-add-card')]")).click();
////    driver.findElement(By.cssSelector(".confirm")).click();
//    js.executeScript("window.scrollTo(0,0)");
//    driver.findElement(By.cssSelector(".icon-edit")).click();
//    driver.findElement(By.cssSelector(".js-archive > .quick-card-editor-buttons-item-text")).click();
//  }
//}
