// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class LogAddDelTest1 extends TestBase{
    AccountData user = new AccountData("marinarhipova5@gmail.com", "53wr67qpt");
    Column column = new Column("Try2");

    @Test
    public void logAddDel() throws InterruptedException {
        getTrello();
        login(user);
        goToTable();
        addColumn(column);
        deleteColumn();
    }

}
