// Generated by Selenium IDE

import itis.bases.TestBase;
import itis.entities.Board;
import itis.helper.BoardHelper;
import itis.helper.ColumnHelper;
import itis.helper.LoginHelper;
import itis.helper.NavigationHelper;
import org.junit.Assert;
import org.junit.Test;

public class TrelloTest extends TestBase {

    @Test
    public void getLoginPageTest() throws Exception {
        getAppManager().getNavigateHelper().getLoginPage();
        getAppManager().getNavigateHelper().checkLoginPageUrl();
        Assert.assertEquals(NavigationHelper.baseUrl, "https://trello.com/home");
    }

    @Test
    public void doLoginTest() throws Exception {
        getLoginPageTest();
        getAppManager().getLoginHelper().doLogin(LoginHelper.USER);
        getAppManager().getLoginHelper().checkUsername();
        Assert.assertEquals(LoginHelper.USERNAME, "MarinArhipova (marinarhipova)");
    }

    @Test
    public void getBoardsPageTest() throws Exception {
        getLoginPageTest();
        getAppManager().getLoginHelper().doLogin(LoginHelper.USER);
        getAppManager().getNavigateHelper().getBoardsPage();
        getAppManager().getNavigateHelper().checkBoardPageUrl();
        Assert.assertEquals(NavigationHelper.boardUrl, "https://trello.com/marinarhipova/boards");
    }

    @Test
    public void addBoardTest() throws Exception {
        getBoardsPageTest();
        getAppManager().getBoardHelper().addBoard();
        Assert.assertTrue(BoardHelper.isAdded);
    }

    @Test
    public void addColumnTest() throws Exception {
        addBoardTest();
        getAppManager().getColumnHelper().addColumn();
        getAppManager().getColumnHelper().checkAddedColumn();
        Assert.assertEquals(ColumnHelper.NAME, "Yessss");
    }

    @Test
    public void deleteColumnTest() throws Exception {
        addColumnTest();
        getAppManager().getColumnHelper().deleteColumn();
        Assert.assertTrue(ColumnHelper.isDeleted);
    }

    @Test
    public void deleteBoardTest() throws Exception {
        deleteColumnTest();
        getAppManager().getBoardHelper().deleteBoard();
        Assert.assertTrue(BoardHelper.isDeleted);
    }

}
